'use client';

import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { RiskIndicator } from '@/components/shared/risk-indicator';
import { Case } from '@/types';
import { getRiskLevel } from '@/lib/constants';
import { aiAnalysisApi } from '@/services/api/ai-analysis-api';
import { Brain, Circle, RefreshCw, Sparkles, AlertTriangle, TrendingUp, Wrench, Shield, Zap, FileDown } from 'lucide-react';
import { cn } from '@/lib/utils';

function downloadReport(caseId: string) {
  fetch(`/api/reports/case/${caseId}`)
    .then((res) => res.blob())
    .then((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `PolitiTrace-${caseId}-Report.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    });
}

interface IntelSummaryProps {
  caseData: Case | null;
}

export function IntelSummary({ caseData }: IntelSummaryProps) {
  const [isRegenerating, setIsRegenerating] = useState(false);
  const queryClient = useQueryClient();

  const { data: analysis } = useQuery({
    queryKey: ['ai', 'case-analysis', caseData?.id],
    queryFn: () => aiAnalysisApi.generateCaseAnalysis(caseData!.id),
    enabled: !!caseData,
  });

  if (!caseData || !analysis) return null;

  const riskLevel = getRiskLevel(caseData.riskScore);

  const handleRegenerate = () => {
    setIsRegenerating(true);
    setTimeout(() => {
      queryClient.invalidateQueries({ queryKey: ['ai', 'case-analysis', caseData.id] });
      setIsRegenerating(false);
    }, 1200);
  };

  return (
    <div className="w-72 shrink-0 border-l flex flex-col">
      <div className="p-3 border-b space-y-2">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold flex items-center gap-2">
            <Brain size={16} className="text-primary" />
            AI Intelligence
          </h3>
          <Button
            variant="ghost"
            size="icon-xs"
            onClick={handleRegenerate}
            disabled={isRegenerating}
            aria-label="Regenerate analysis"
          >
            <RefreshCw size={12} className={cn(isRegenerating && 'animate-spin')} />
          </Button>
        </div>
        <div className="flex items-center gap-1.5 mt-1">
          <Sparkles size={10} className="text-primary" />
          <span className="text-[10px] text-muted-foreground">
            AI Confidence: {analysis.confidence}%
          </span>
          <div className="flex-1" />
          <div
            className={cn(
              'h-1.5 w-1.5 rounded-full',
              analysis.confidence >= 85 ? 'bg-low' : analysis.confidence >= 70 ? 'bg-medium' : 'bg-high',
            )}
          />
        </div>

        {/* Export PDF Button */}
        <Button
          variant="outline"
          size="sm"
          className="w-full gap-1.5 text-xs"
          onClick={() => downloadReport(caseData.id)}
        >
          <FileDown size={12} />
          Export PDF Report
        </Button>

        {/* Agent attribution */}
        <div className="rounded-md bg-primary/5 border border-primary/15 px-2 py-1.5">
          <div className="flex items-center gap-1.5 mb-1">
            <Shield size={9} className="text-primary" />
            <span className="text-[9px] font-semibold text-primary uppercase tracking-wider">Investigation Agent</span>
          </div>
          <div className="flex flex-wrap gap-1">
            {['get_case_details', 'query_entities', 'calculate_entity_risk', 'build_case_timeline'].map((tool) => (
              <span key={tool} className="inline-flex items-center gap-0.5 rounded bg-muted px-1 py-0.5 text-[8px] font-mono text-muted-foreground">
                <Wrench size={7} />
                {tool}
              </span>
            ))}
          </div>
        </div>
      </div>

      <ScrollArea className="flex-1">
        <div className={cn('p-3 space-y-4', isRegenerating && 'opacity-50 pointer-events-none')}>
          {/* What is this */}
          <div className="rounded-md bg-muted/40 px-2.5 py-1.5">
            <p className="text-[10px] text-muted-foreground leading-relaxed">
              This panel is generated by AI based on the actual entities, alerts, and evidence linked to this case. Risk factors, patterns, and recommendations update per case. Hit the refresh icon above to regenerate.
            </p>
          </div>

          {/* Risk Score */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs font-medium text-muted-foreground">Overall Risk</span>
              <span className={cn('text-2xl font-bold', `text-${riskLevel}`)}>{caseData.riskScore}</span>
            </div>
            <RiskIndicator score={caseData.riskScore} size="lg" />
          </div>

          <Separator />

          {/* Risk Factors (dynamic from AI) */}
          <div>
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Contributing Factors</h4>
            <div className="space-y-3">
              {analysis.riskFactors.map((factor) => (
                <div key={factor.name}>
                  <div className="flex items-center justify-between text-xs mb-1">
                    <span>{factor.name}</span>
                    <span className="font-mono">{factor.score}%</span>
                  </div>
                  <Progress value={factor.score} className="h-1.5" />
                  <span className="text-[10px] text-muted-foreground">Weight: {factor.weight}%</span>
                </div>
              ))}
            </div>
          </div>

          <Separator />

          {/* AI Analysis (dynamic) */}
          <div>
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Sparkles size={10} className="text-primary" />
              AI Analysis
            </h4>
            <p className="text-sm leading-relaxed">{analysis.summary}</p>
          </div>

          {/* Detected Patterns */}
          {analysis.patterns.length > 0 && (
            <>
              <Separator />
              <div>
                <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <TrendingUp size={10} />
                  Detected Patterns
                </h4>
                <div className="space-y-1.5">
                  {analysis.patterns.map((pattern, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs">
                      <AlertTriangle size={10} className="text-high shrink-0" />
                      <span>{pattern}</span>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}

          <Separator />

          {/* Recommended Actions (dynamic) */}
          <div>
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Recommended Actions</h4>
            <div className="space-y-2">
              {analysis.recommendations.map((rec, i) => (
                <div key={i} className="flex items-start gap-2">
                  {rec.priority === 'high' ? (
                    <AlertTriangle size={14} className="text-high mt-0.5 shrink-0" />
                  ) : (
                    <Circle size={14} className="text-muted-foreground mt-0.5 shrink-0" />
                  )}
                  <div>
                    <span className="text-xs">{rec.text}</span>
                    <Badge variant="outline" className="ml-1 text-[8px] capitalize">{rec.category}</Badge>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <Separator />

          {/* Tags */}
          <div>
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Tags</h4>
            <div className="flex flex-wrap gap-1">
              {caseData.tags.map((tag) => (
                <Badge key={tag} variant="secondary" className="text-[10px]">{tag}</Badge>
              ))}
            </div>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
